# Instruct Travis to build PRs as well as merges
# to master. See https://stackoverflow.com/a/31882307/145400.
branches:
  only:
    - master

os:
  - linux
  - osx

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

# Try to work around Travis' lack of Python support on OS X.
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791
matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate

install:
  - pip install .
  - pip install -r requirements-tests.txt

script:
    - python --version && uname -a && pip list
    - echo "Test with gevent 1.3.x"
    - pytest -vv test/
    - bash examples/run-all.sh
    - echo "Re-test with gevent 1.2.x"
    - pip install 'gevent>=1.2,<1.3' --upgrade
    - pytest -vv test/
    - bash examples/run-all.sh
    - bash audit.sh
